# Generated by Django 6.0.5 on 2026-05-29 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('affected_system', models.CharField(max_length=255)),
                ('rollback_plan', models.TextField()),
                ('deployment_window', models.DateTimeField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deployed', 'Deployed')], default='draft', max_length=20)),
                ('submitted_by', models.CharField(max_length=255)),
                ('ingestion_batch_id', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'it_change_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('p1', 'P1 — Critical'), ('p2', 'P2 — High'), ('p3', 'P3 — Medium'), ('p4', 'P4 — Low')], max_length=5)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('affected_system', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'it_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('service_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'it_vendors',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('license_key', models.CharField(blank=True, max_length=255)),
                ('seats', models.IntegerField(default=1)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domains_it.vendor')),
            ],
            options={
                'db_table': 'it_software_licenses',
                'ordering': ['expiry_date'],
            },
        ),
    ]
