# Generated by Django 6.0.5 on 2026-06-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tenantmembership_user_and_more'),
        ('domains_it', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='it_vendors', to='core.tenant'),
        ),
    ]
