# Generated by Django 6.0.5 on 2026-05-27 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('finance', 'Finance & Wealth Management'), ('it', 'IT / Technology'), ('hr', 'HR / People Operations'), ('legal', 'Legal'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('education', 'Education'), ('government', 'Government / Public Sector'), ('energy', 'Energy'), ('telecom', 'Telecom'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics / Supply Chain'), ('retail', 'Retail / E-commerce'), ('cybersecurity', 'Cybersecurity')], max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('reviewer', 'Reviewer'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_memberships',
            },
        ),
    ]
