# Generated by Django 6.0.5 on 2026-05-28 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('risk_tolerance', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument_uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('asset_class', models.CharField(choices=[('equity', 'Equity'), ('fixed_income', 'Fixed Income'), ('etf', 'ETF'), ('cash', 'Cash'), ('alternative', 'Alternative')], max_length=20)),
                ('risk_score', models.IntegerField(default=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'instruments',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='domains.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('tx_date', models.DateField()),
                ('ingestion_batch_id', models.CharField(blank=True, max_length=64)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domains.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='domains.portfolio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-tx_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('average_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('ingestion_batch_id', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domains.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='domains.portfolio')),
            ],
            options={
                'db_table': 'holdings',
                'unique_together': {('portfolio', 'instrument')},
            },
        ),
    ]
