# Generated by Django 6.0.5 on 2026-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tenantmembership_user_and_more'),
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('tenant', 'instrument_uid')},
        ),
    ]
