# Generated by Django 6.0.5 on 2026-05-27 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='MemoryPayload',
            fields=[
                ('content_hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('content', models.JSONField()),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('pii_class', models.CharField(choices=[('none', 'No PII'), ('low', 'Low sensitivity'), ('high', 'High sensitivity'), ('critical', 'Critical / regulated PII')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'memory_payloads',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_version', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_for_input', 'Waiting for Input'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating')], default='pending', max_length=30)),
                ('graph_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='engine.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'workflow_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_code', models.CharField(max_length=100)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('input_ref', models.CharField(blank=True, max_length=64)),
                ('output_ref', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.IntegerField(null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_runs', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'node_runs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HumanAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_code', models.CharField(max_length=100)),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('justification', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_actions', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'human_actions',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_code', models.CharField(max_length=100)),
                ('options', models.JSONField(default=list)),
                ('selected', models.JSONField(default=dict)),
                ('decision_basis', models.TextField(blank=True)),
                ('quality_signals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'decision_points',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(max_length=255)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('output_summary', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('workflow_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_run', to='engine.workflowrun')),
            ],
            options={
                'db_table': 'agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(max_length=50)),
                ('graph_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['code', '-version'],
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='agent',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='engine.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='TenantWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overrides', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.workflowtemplate')),
            ],
            options={
                'db_table': 'tenant_workflow_configs',
                'unique_together': {('tenant', 'template')},
            },
        ),
    ]
