# Generated by Django 6.0.5 on 2026-05-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='sector',
            field=models.CharField(choices=[('finance', 'Finance & Wealth Management'), ('it', 'IT / Technology'), ('hr', 'HR / People Operations'), ('legal', 'Legal'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('education', 'Education'), ('government', 'Government / Public Sector'), ('energy', 'Energy'), ('telecom', 'Telecom'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics / Supply Chain'), ('retail', 'Retail / E-commerce'), ('cybersecurity', 'Cybersecurity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='sector',
            field=models.CharField(choices=[('finance', 'Finance & Wealth Management'), ('it', 'IT / Technology'), ('hr', 'HR / People Operations'), ('legal', 'Legal'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('education', 'Education'), ('government', 'Government / Public Sector'), ('energy', 'Energy'), ('telecom', 'Telecom'), ('manufacturing', 'Manufacturing'), ('logistics', 'Logistics / Supply Chain'), ('retail', 'Retail / E-commerce'), ('cybersecurity', 'Cybersecurity')], max_length=50),
        ),
    ]
