# Generated by Django 6.0.5 on 2026-06-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_agent_sector_alter_workflowtemplate_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together={('sector', 'code')},
        ),
    ]
