# Generated by Django 6.0.5 on 2026-06-03 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tenantmembership_user_and_more'),
        ('engine', '0004_toolcall_policyevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyevaluation',
            old_name='evidence',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='toolcall',
            old_name='error_message',
            new_name='error',
        ),
        migrations.RenameField(
            model_name='toolcall',
            old_name='input_payload',
            new_name='input_data',
        ),
        migrations.RenameField(
            model_name='toolcall',
            old_name='output_payload',
            new_name='output_data',
        ),
        migrations.RemoveField(
            model_name='policyevaluation',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='policyevaluation',
            name='policy_version',
        ),
        migrations.RemoveField(
            model_name='policyevaluation',
            name='rationale',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='node_run',
        ),
        migrations.RemoveField(
            model_name='toolcall',
            name='tool_version',
        ),
        migrations.AddField(
            model_name='policyevaluation',
            name='policy_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='policyevaluation',
            name='result',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARN', 'Warning'), ('SKIPPED', 'Skipped')], default='PASS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcall',
            name='node_code',
            field=models.CharField(default='PASS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcall',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolcall',
            name='workflow_run',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='engine.workflowrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyevaluation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolcall',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='toolcall',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolcall',
            name='status',
            field=models.CharField(default='success', max_length=20),
        ),
    ]
